### ISSUE TITLE
🎙️Call for speakers for GraphQL Singapore meetup [2019]

### ISSUE THREAD

**Issue by graphql-sg** [graphql-sg/graphql-sg.github.io#1]
👏Hi! Thanks for your interest in giving a speak in GraphQL Singapore meetup! Please kindly leave your ideas below as a new reply.

## I want to submit my talk here!

Please leave a comment below about your talk with the following details:

> ### ${Title}
> `One sentence description about your talk`
> ### ${Presenter[s]}
> `A brief introduction about yourself, Github or LinkedIn link could be added here`
> ### ${Content}
> `More detailed content of your talk, so that audiences can have an idea about your talk > before hearing`
> (Please note that we prefer the talks to be around 15 minutes, and leave some time for Q&A)
> ### ${Slides}(good to have)
> `A link to your slides, possibly Google Slides or Google Drive link`

**Comment by markselby9** [comment]
### Title: GraphQL Singapore meetup kick-off
First talk in GraphQL Singapore 🇸🇬 to kick off!

### Presenter: Mark
Organizer of the meetup, https://github.com/markselby9

### Content

1. Self introduction, and bootstrap information about this meetup
2. A workshop to play with Github GraphQL API
3. A live-coding walkthrough (from OSCON 2018)
4. Q&A, chat

### Slides: 
https://docs.google.com/presentation/d/18nglCeMJR-a18MmaYlRc_RqXWPlrugKtdDUZUGQDxOI/edit?usp=sharing
